database:
  filename: gambling.db

bot:
  token: INSERT API TOKEN HERE
  dev_mode: false

game_settings:
  slot_machine:
    paytable: [
      {"combo": ["7ï¸âƒ£", "7ï¸âƒ£", "7ï¸âƒ£"], "payout_mult": 80},
      {"combo": ["â—¼ï¸", "â—¼ï¸", "â—¼ï¸"], "payout_mult": 40},
      {"combo": ["ğŸ‹", "ğŸ‹", "ğŸ‹"], "payout_mult": 10},
      {"combo": ["ğŸ‡", "ğŸ‡", "ğŸ‡"], "payout_mult": 10},
      {"combo": ["â—¼ï¸", "â—¼ï¸", ""], "payout_mult": 1}
    ]
    bet_cents: 25

